version: '3'
services:
  java-backend:
    build:
      context: ./java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./productsDB
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - h2

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  h2:
    image: oscarfonts/h2
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      - H2_OPTIONS=-ifNotExists
