version: '3'
services:
  server:
    build:
     context: ./java
     dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
      db_user_name: sa
      db_password: 
    container_name: java
  ui:
    build:
     context: ./react
     dockerfile: Dockerfile
    ports:
     - "3000:3000"
    environment:
      server_db_url: jdbc:h2:file:./productsDB
      server_db_user_name: sa
      server_db_password: 
    container_name: react
