version: '3'
services:
  java:
      build:
        context: ./java
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
  react:
      build:
        context: ./react
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
