version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment: 
      MYSQL_USER: sa
      MYSQL_PASSWORD: 

  java:
      build:
        context: ./java
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:h2:file:./productsDB
        SPRING_DATASOURCE_USERNAME: sa
        SPRING_DATASOURCE_PASSWORD: 

  react:
      build:
        context: ./react
        dockerfile: Dockerfile
      ports:
        - "3000:80"
