version: '3'
services:
  db:
      image: 
      ports: 
        - ""
      environment:
        db_user: sa
        db_password:
  java:
      build:
        context: ./java
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - db
      environment:
        db_url: jdbc:h2:file:./productsDB
        db_user_name: sa
        db_password:
  react:
      build:
        context: ./react
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
